/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yumi_encryptlibrary_encrypt_EncryptUtils */

#ifndef _Included_com_yumi_encryptlibrary_encrypt_EncryptUtils
#define _Included_com_yumi_encryptlibrary_encrypt_EncryptUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yumi_encryptlibrary_encrypt_EncryptUtils
 * Method:    encryptAES
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_yumi_encryptlibrary_encrypt_EncryptUtils_encryptAES
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_yumi_encryptlibrary_encrypt_EncryptUtils
 * Method:    encryptMD5
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_yumi_encryptlibrary_encrypt_EncryptUtils_encryptMD5
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_yumi_encryptlibrary_encrypt_EncryptUtils
 * Method:    decryptAES
* Signature: (Ljava/lang/String;)Ljava/lang/String;
*/
JNIEXPORT jstring JNICALL Java_com_yumi_encryptlibrary_encrypt_EncryptUtils_decryptAES
        (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
